apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: celery-worker
    spec:
      containers:
        - args:
            - /bin/sh
            - /app/deployment/scripts/celery/start-worker.sh
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: ALLOWED_HOSTS
                  name: env
            - name: APP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: APP_DOMAIN
                  name: env
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  key: APP_ENV
                  name: env
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  key: APP_HOST
                  name: env
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_NAME
                  name: env
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_PORT
                  name: env
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: CORS_ALLOWED_ORIGINS
                  name: env
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: CSRF_TRUSTED_ORIGINS
                  name: env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: env
            - name: LETSENCRYPT_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: LETSENCRYPT_EMAIL
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: env
          image: celery-worker
          name: celery-worker
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/
              name: celery-worker-claim0
            - mountPath: /app/deployment/scripts/
              name: celery-worker-claim1
      restartPolicy: Always
      volumes:
        - name: celery-worker-claim0
          persistentVolumeClaim:
            claimName: celery-worker-claim0
        - name: celery-worker-claim1
          persistentVolumeClaim:
            claimName: celery-worker-claim1
status: {}
