apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db-slave
  name: db-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-slave
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: db-slave
    spec:
      containers:
        - env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: ALLOWED_HOSTS
                  name: env
            - name: APP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: APP_DOMAIN
                  name: env
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  key: APP_ENV
                  name: env
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  key: APP_HOST
                  name: env
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_NAME
                  name: env
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_PORT
                  name: env
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: CORS_ALLOWED_ORIGINS
                  name: env
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: CSRF_TRUSTED_ORIGINS
                  name: env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: env
            - name: LETSENCRYPT_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: LETSENCRYPT_EMAIL
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_MASTER_HOST
              value: postgres_master
            - name: POSTGRES_MASTER_PORT
              value: "5432"
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: env
          image: postgres:15.2-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - postgres
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: db-slave
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgres-data-dir
      hostname: db-slave
      restartPolicy: Always
      volumes:
        - name: postgres-data-dir
          persistentVolumeClaim:
            claimName: postgres-data-dir
status: {}
